@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('download')
        {
            steps
            {
                script
                {
                cicd.download("maven")
                }
            }
        }
        stage('build')
        {
            steps
            {
                script
                {
                    cicd.build()
                }
            }
        }
        stage('depploy')
        {
            steps
            {
                script
                {
                    cicd.deploy("DeclarativePipeline","172.31.28.158","mytestapp")
                }
            }    
        }
        stage('test')
        {
            steps
            {
                script
                {
                    cicd.download("FunctionalTesting")
                    cicd.runselenium("DeclarativePipeline")
                }
            }
        }
        stage('delivery')
        {
            steps
            {
                script
                {
                    cicd.deploy("DeclarativePipeline","172.31.28.158","myprodapp")
                }
            }
        }
    }
}
