@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('download')
        {
            steps
            {
                script
                {
                cicd.download("maven")
                }
            }
        }
        stage('build')
        {
            steps
            {
                script
                {
                    cicd.build()
                }
            }
        }
    }
}
